name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    example:
      +materialized: table
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table
      finance:
        +schema: finance
  +location: EU   # dikkat: bu satır proje isminin altında

seeds:
  +location: EU

snapshots:
  +location: EU
