version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales of Greenweez / one row per product_id found in each orders_id

        # Freshness testi için
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}

        columns:
          - name: date_date
            description: Date of purchase
          - name: orders_id
            description: Unique ID of the order
          - name: pdt_id
            description: Product identifier (foreign key to product table)
          - name: revenue
            description: Revenue for this product in this order
          - name: quantity
            description: Number of units purchased

        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_products
        description: Product catalog of Greenweez
        columns:
          - name: products_id
            description: Unique product ID
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: Purchase price of the product (to be cast as FLOAT64)

      - name: ship
        identifier: raw_gz_ship
        description: Shipping details for each order
        columns:
          - name: orders_id
            description: Primary key of the ship table (unique order ID)
            tests:
              - unique
              - not_null
          - name: ship_cost
            description: Shipping cost of the order (FLOAT64)
          - name: shipping_fee
            description: Fee charged for shipping (FLOAT64)
          - name: shipping_fee_1
            description: Duplicate of shipping_fee (kept for source reference, cleaned in staging)
          - name: logcost
            description: Logistic cost of the order (FLOAT64)

      # Yeni eklenen reklam kaynakları
      - name: adwords
        identifier: raw_gz_adwords
        description: Google AdWords campaign data
        meta:
          company: Google

      - name: bing
        identifier: raw_gz_bing
        description: Microsoft Bing Ads campaign data
        meta:
          company: Microsoft

      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo campaign data
        meta:
          company: Criteo

      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook Ads campaign data
        meta:
          company: Meta

models:
  - name: finance_campaigns_day
    description: "Daily finance data enriched with advertising costs and ads_margin calculation"
    columns:
      - name: date_date
        description: "Date of aggregation (daily level)"
        tests:
          - not_null

      - name: ads_margin
        description: "Operational margin minus advertising cost"

      - name: average_basket
        description: "Average basket size (revenue per transaction)"

      - name: operational_margin
        description: "Operational margin (revenue - purchase cost - logistics - shipping)"

      - name: ads_cost
        description: "Total advertising cost for the day"

      - name: ads_impression
        description: "Total number of ad impressions for the day"

      - name: ads_click
        description: "Total number of ad clicks for the day"

      - name: total_quantity_sold
        description: "Total quantity of products sold"

      - name: total_revenue
        description: "Total revenue generated in the day"

      - name: total_purchase_cost
        description: "Total purchase cost of products sold"

      - name: total_margin
        description: "Total margin before ads"

      - name: total_shipping_fees
        description: "Total shipping fees charged to customers"

      - name: total_log_costs
        description: "Total logistic costs incurred"

      - name: total_ship_cost
        description: "Total shipping costs paid by the company"
          
  - name: int_campaigns
    description: "Intermediate model combining Adwords, Bing, Criteo and Facebook campaign data into a unified structure"
    columns:
      - name: campaign_key
        description: "Unique identifier of the campaign"
        tests:
          - not_null

      - name: paid_source
        description: "Source platform of the campaign (Adwords, Bing, Criteo, Facebook)"
        tests:
          - not_null

      - name: date_date
        description: "Date of the campaign activity"
        tests:
          - not_null

      - name: campaign_name
        description: "Normalized name of the campaign"
        tests:
          - not_null

      - name: ads_cost
        description: "Advertising cost (FLOAT64)"
        tests:
          - not_null

      - name: impression
        description: "Number of impressions served by the campaign"
        tests:
          - not_null

      - name: click
        description: "Number of clicks generated by the campaign"
        tests:
          - not_null

    tests:
      - unique:
          column_name: "(campaign_key || '-' || paid_source || '-' || date_date)"

  - name: int_campaigns_day
    description: "Daily aggregated campaign data from int_campaigns"
    columns:
      - name: date_date
        description: "Date of the campaign activity"
        tests:
          - not_null
      - name: campaign_key
        description: "Campaign identifier"
        tests:
          - not_null
      - name: paid_source
        description: "Source of the campaign"
        tests:
          - not_null
      - name: total_ads_cost
        description: "Total advertising cost aggregated per day"
      - name: total_impressions
        description: "Total impressions aggregated per day"
      - name: total_clicks
        description: "Total clicks aggregated per day"
